#!/bin/bash
# build_and_test.sh - Full rebuild and test for M65832 picolibc
#
# Ensures reproducible test results by rebuilding everything from scratch:
# 1. Compiler-rt (soft int64, soft float)
# 2. Picolibc (libc)
# 3. M65832-specific startup (crt0, syscalls, linker script)
# 4. Installs all to sysroot
# 5. Runs picolibc test suite and saves timestamped results
#
# Usage:
#   ./build_and_test.sh              Full rebuild + test
#   ./build_and_test.sh --skip-build Just run tests (use existing sysroot)
#   ./build_and_test.sh --filter=mem Run only tests matching "mem"

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECTS_DIR="$(dirname "$SCRIPT_DIR")"

# Paths
LLVM_ROOT="$PROJECTS_DIR/llvm-m65832"
LLVM_BUILD="$LLVM_ROOT/build-fast"
PICOLIBC_SRC="$SCRIPT_DIR"
PICOLIBC_BUILD="$PROJECTS_DIR/picolibc-build-m65832"
SYSROOT="$PROJECTS_DIR/m65832-sysroot"
COMPILER_RT_DIR="$LLVM_ROOT/m65832-stdlib/compiler-rt"
M65832_STDLIB="$LLVM_ROOT/m65832-stdlib"
M65832_PICOLIBC="$M65832_STDLIB/picolibc"
TEST_RESULTS_DIR="$SCRIPT_DIR/test-results"

# Tools
CLANG="$LLVM_BUILD/bin/clang"
CROSS_FILE="$M65832_PICOLIBC/cross-m65832.txt"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
BOLD='\033[1m'
NC='\033[0m'

# Parse arguments
SKIP_BUILD=false
TEST_ARGS=""
while [[ $# -gt 0 ]]; do
    case $1 in
        --skip-build)
            SKIP_BUILD=true
            shift
            ;;
        *)
            TEST_ARGS="$TEST_ARGS $1"
            shift
            ;;
    esac
done

echo -e "${BOLD}=========================================="
echo "M65832 Build and Test"
echo -e "==========================================${NC}"
echo ""
echo "Compiler:    $CLANG"
echo "Picolibc:    $PICOLIBC_SRC"
echo "Build:       $PICOLIBC_BUILD"
echo "Sysroot:     $SYSROOT"
echo "Compiler-RT: $COMPILER_RT_DIR"
echo ""

# Verify tools exist
if [ ! -x "$CLANG" ]; then
    echo -e "${RED}ERROR: clang not found at $CLANG${NC}"
    exit 1
fi
if ! command -v meson &> /dev/null; then
    echo -e "${RED}ERROR: meson not found${NC}"
    exit 1
fi

if [ "$SKIP_BUILD" = false ]; then

    # =========================================================
    # Step 1: Rebuild compiler-rt
    # =========================================================
    echo -e "\n${BOLD}>>> Step 1/5: Rebuilding compiler-rt...${NC}"
    cd "$COMPILER_RT_DIR"
    make clean 2>/dev/null || true
    make -j8
    echo -e "${GREEN}    compiler-rt built${NC}"

    # Install to sysroot so picolibc build can find it
    mkdir -p "$SYSROOT/lib"
    cp "$COMPILER_RT_DIR/libcompiler_rt.a" "$SYSROOT/lib/"
    echo -e "${GREEN}    installed to sysroot${NC}"

    # =========================================================
    # Step 2: Regenerate cross-compilation config
    #   (build_picolibc.sh does this; we replicate exactly)
    # =========================================================
    echo -e "\n${BOLD}>>> Step 2/5: Generating cross-compilation config...${NC}"
    cat > "$M65832_PICOLIBC/m65832-clang" << 'CLANG_WRAPPER_EOF'
#!/bin/bash
# Wrapper for clang that adds M65832 target flags
# Adds our fake gcc to PATH so clang's linker driver uses ld.lld
CLANG_WRAPPER_EOF
    cat >> "$M65832_PICOLIBC/m65832-clang" << EOF
CLANG=$CLANG
WRAPPER_DIR=$M65832_PICOLIBC

# Put our fake gcc first in PATH
export PATH="\$WRAPPER_DIR:\$PATH"

exec "\$CLANG" \\
    -target m65832-elf \\
    -ffreestanding \\
    -mllvm -disable-peephole \\
    -nostdlib \\
    -L$SYSROOT/lib \\
    -lcompiler_rt \\
    -fuse-ld=$M65832_PICOLIBC/m65832-gcc \\
    "\$@"
EOF
    chmod +x "$M65832_PICOLIBC/m65832-clang"

    cat > "$CROSS_FILE" << EOF
# Meson cross-compilation file for M65832
# Auto-generated by build_and_test.sh

[constants]
stdlib_dir = '$M65832_STDLIB'

[binaries]
c = '$M65832_PICOLIBC/m65832-clang'
ar = 'ar'
as = '$M65832_PICOLIBC/m65832-clang'
ld = '$LLVM_BUILD/bin/ld.lld'
strip = 'strip'
ranlib = 'ranlib'
exe_wrapper = ['$M65832_PICOLIBC/run-m65832.sh']

[built-in options]
# Note: -g disabled due to debug info crash in MCAssembler::layout() - bug to fix
# Note: -O2+ disabled due to analyzeBranch() crash in BranchFolder - bug to fix
c_args = ['-O1', '-nostdlib']
c_link_args = ['-L$SYSROOT/lib',
               '-lcompiler_rt']

[host_machine]
system = 'none'
cpu_family = 'm65832'
cpu = 'm65832'
endian = 'little'

[properties]
skip_sanity_check = true
default_ram_size = '0x00020000'
default_noflash_ram_size = '0x00020000'
default_flash_size = '0x00200000'
default_noflash_flash_size = '0x00200000'
default_flash_addr = '0x00000000'
default_ram_addr = '0x00200000'
default_noflash_flash_addr = '0x00000000'
default_noflash_ram_addr = '0x00000000'
EOF
    echo -e "${GREEN}    cross config generated${NC}"

    # =========================================================
    # Step 3: Clean rebuild picolibc (matching original config)
    # =========================================================
    echo -e "\n${BOLD}>>> Step 3/5: Clean rebuilding picolibc...${NC}"
    rm -rf "$PICOLIBC_BUILD"

    meson setup "$PICOLIBC_BUILD" "$PICOLIBC_SRC" \
        --cross-file "$CROSS_FILE" \
        --prefix="$SYSROOT" \
        --buildtype=plain \
        -Ddebug=false \
        -Doptimization=1 \
        -Dmultilib=false \
        -Dtests=false \
        -Dprintf-aliases=false \
        -Dspecsdir=none \
        -Dfreestanding=true \
        -Dio-float-exact=false  # dtoa_ryu.c hits regalloc crash (compiler bug to fix separately)

    meson compile -C "$PICOLIBC_BUILD" -j8
    echo -e "${GREEN}    picolibc built${NC}"

    echo -e "\n${BOLD}Build complete.${NC}"
    echo "Build dir: $PICOLIBC_BUILD"
    echo "Note: WIP builds are NOT installed to sysroot."
    echo "      Tests use build directories directly."
fi

# =========================================================
# Step 4: Run tests (using build directories, not sysroot)
# =========================================================
echo -e "\n${BOLD}>>> Running tests...${NC}"
cd "$SCRIPT_DIR"

mkdir -p "$TEST_RESULTS_DIR"

# Run tests using build directories directly (no sysroot installation)
python3 run_picolibc_gtest.py --no-rebuild $TEST_ARGS

echo ""
