/*
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Copyright © 2026 Keith Packard
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef _LINUX_ERRNO_H_
#define _LINUX_ERRNO_H_

#define LINUX_ERRNO_EPERM 1
#define LINUX_ERRNO_ENOENT 2
#define LINUX_ERRNO_ESRCH 3
#define LINUX_ERRNO_EINTR 4
#define LINUX_ERRNO_EIO 5
#define LINUX_ERRNO_ENXIO 6
#define LINUX_ERRNO_E2BIG 7
#define LINUX_ERRNO_ENOEXEC 8
#define LINUX_ERRNO_EBADF 9
#define LINUX_ERRNO_ECHILD 10
#define LINUX_ERRNO_EAGAIN 11
#define LINUX_ERRNO_ENOMEM 12
#define LINUX_ERRNO_EACCES 13
#define LINUX_ERRNO_EFAULT 14
#define LINUX_ERRNO_ENOTBLK 15
#define LINUX_ERRNO_EBUSY 16
#define LINUX_ERRNO_EEXIST 17
#define LINUX_ERRNO_EXDEV 18
#define LINUX_ERRNO_ENODEV 19
#define LINUX_ERRNO_ENOTDIR 20
#define LINUX_ERRNO_EISDIR 21
#define LINUX_ERRNO_EINVAL 22
#define LINUX_ERRNO_ENFILE 23
#define LINUX_ERRNO_EMFILE 24
#define LINUX_ERRNO_ENOTTY 25
#define LINUX_ERRNO_ETXTBSY 26
#define LINUX_ERRNO_EFBIG 27
#define LINUX_ERRNO_ENOSPC 28
#define LINUX_ERRNO_ESPIPE 29
#define LINUX_ERRNO_EROFS 30
#define LINUX_ERRNO_EMLINK 31
#define LINUX_ERRNO_EPIPE 32
#define LINUX_ERRNO_EDOM 33
#define LINUX_ERRNO_ERANGE 34
#define LINUX_ERRNO_ENOMSG 35
#define LINUX_ERRNO_EIDRM 36
#define LINUX_ERRNO_ECHRNG 37
#define LINUX_ERRNO_EL2NSYNC 38
#define LINUX_ERRNO_EL3HLT 39
#define LINUX_ERRNO_EL3RST 40
#define LINUX_ERRNO_ELNRNG 41
#define LINUX_ERRNO_EUNATCH 42
#define LINUX_ERRNO_ENOCSI 43
#define LINUX_ERRNO_EL2HLT 44
#define LINUX_ERRNO_EDEADLK 45
#define LINUX_ERRNO_ENOLCK 46
#define LINUX_ERRNO_EBADE 50
#define LINUX_ERRNO_EBADR 51
#define LINUX_ERRNO_EXFULL 52
#define LINUX_ERRNO_ENOANO 53
#define LINUX_ERRNO_EBADRQC 54
#define LINUX_ERRNO_EBADSLT 55
#define LINUX_ERRNO_EDEADLOCK 56
#define LINUX_ERRNO_EBFONT 57
#define LINUX_ERRNO_ENOSTR 60
#define LINUX_ERRNO_ENODATA 61
#define LINUX_ERRNO_ETIME 62
#define LINUX_ERRNO_ENOSR 63
#define LINUX_ERRNO_ENONET 64
#define LINUX_ERRNO_ENOPKG 65
#define LINUX_ERRNO_EREMOTE 66
#define LINUX_ERRNO_ENOLINK 67
#define LINUX_ERRNO_EADV 68
#define LINUX_ERRNO_ESRMNT 69
#define LINUX_ERRNO_ECOMM 70
#define LINUX_ERRNO_EPROTO 71
#define LINUX_ERRNO_EMULTIHOP 74
#define LINUX_ERRNO_ELBIN 75
#define LINUX_ERRNO_EDOTDOT 76
#define LINUX_ERRNO_EBADMSG 77
#define LINUX_ERRNO_EFTYPE 79
#define LINUX_ERRNO_ENOTUNIQ 80
#define LINUX_ERRNO_EBADFD 81
#define LINUX_ERRNO_EREMCHG 82
#define LINUX_ERRNO_ELIBACC 83
#define LINUX_ERRNO_ELIBBAD 84
#define LINUX_ERRNO_ELIBSCN 85
#define LINUX_ERRNO_ELIBMAX 86
#define LINUX_ERRNO_ELIBEXEC 87
#define LINUX_ERRNO_ENOSYS 88
#define LINUX_ERRNO_ENMFILE 89
#define LINUX_ERRNO_ENOTEMPTY 90
#define LINUX_ERRNO_ENAMETOOLONG 91
#define LINUX_ERRNO_ELOOP 92
#define LINUX_ERRNO_EOPNOTSUPP 95
#define LINUX_ERRNO_EPFNOSUPPORT 96
#define LINUX_ERRNO_ECONNRESET 104
#define LINUX_ERRNO_ENOBUFS 105
#define LINUX_ERRNO_EAFNOSUPPORT 106
#define LINUX_ERRNO_EPROTOTYPE 107
#define LINUX_ERRNO_ENOTSOCK 108
#define LINUX_ERRNO_ENOPROTOOPT 109
#define LINUX_ERRNO_ESHUTDOWN 110
#define LINUX_ERRNO_ECONNREFUSED 111
#define LINUX_ERRNO_EADDRINUSE 112
#define LINUX_ERRNO_ECONNABORTED 113
#define LINUX_ERRNO_ENETUNREACH 114
#define LINUX_ERRNO_ENETDOWN 115
#define LINUX_ERRNO_ETIMEDOUT 116
#define LINUX_ERRNO_EHOSTDOWN 117
#define LINUX_ERRNO_EHOSTUNREACH 118
#define LINUX_ERRNO_EINPROGRESS 119
#define LINUX_ERRNO_EALREADY 120
#define LINUX_ERRNO_EDESTADDRREQ 121
#define LINUX_ERRNO_EMSGSIZE 122
#define LINUX_ERRNO_EPROTONOSUPPORT 123
#define LINUX_ERRNO_ESOCKTNOSUPPORT 124
#define LINUX_ERRNO_EADDRNOTAVAIL 125
#define LINUX_ERRNO_ENETRESET 126
#define LINUX_ERRNO_EISCONN 127
#define LINUX_ERRNO_ENOTCONN 128
#define LINUX_ERRNO_ETOOMANYREFS 129
#define LINUX_ERRNO_EPROCLIM 130
#define LINUX_ERRNO_EUSERS 131
#define LINUX_ERRNO_EDQUOT 132
#define LINUX_ERRNO_ESTALE 133
#define LINUX_ERRNO_ENOTSUP 134
#define LINUX_ERRNO_ENOMEDIUM 135
#define LINUX_ERRNO_ENOSHARE 136
#define LINUX_ERRNO_ECASECLASH 137
#define LINUX_ERRNO_EILSEQ 138
#define LINUX_ERRNO_EOVERFLOW 139
#define LINUX_ERRNO_ECANCELED 140
#define LINUX_ERRNO_ENOTRECOVERABLE 141
#define LINUX_ERRNO_EOWNERDEAD 142
#define LINUX_ERRNO_ESTRPIPE 143
#define LINUX_ERRNO_EHWPOISON 144
#define LINUX_ERRNO_EISNAM 145
#define LINUX_ERRNO_EKEYEXPIRED 146
#define LINUX_ERRNO_EKEYREJECTED 147
#define LINUX_ERRNO_EKEYREVOKED 148

#endif /* _LINUX_ERRNO_H_ */
